// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOC126zYedj8rXHbT-WdXs5NVcSucp2I',
    appId: '1:936561383152:web:cb391fa68286fe9f61d435',
    messagingSenderId: '936561383152',
    projectId: 'forbidden-area-app',
    authDomain: 'forbidden-area-app.firebaseapp.com',
    storageBucket: 'forbidden-area-app.firebasestorage.app',
    measurementId: 'G-2BK58Z4PB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs6pNypLsP5wEFvjJmX-teQtek2rw-1gA',
    appId: '1:936561383152:android:7f28895da99845e461d435',
    messagingSenderId: '936561383152',
    projectId: 'forbidden-area-app',
    storageBucket: 'forbidden-area-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTsQv_8_m9nozrcHdriWP0EZxf6MMaHE',
    appId: '1:936561383152:ios:22dfbe1acbc6271d61d435',
    messagingSenderId: '936561383152',
    projectId: 'forbidden-area-app',
    storageBucket: 'forbidden-area-app.firebasestorage.app',
    iosBundleId: 'com.example.forbiddenAreaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjTsQv_8_m9nozrcHdriWP0EZxf6MMaHE',
    appId: '1:936561383152:ios:22dfbe1acbc6271d61d435',
    messagingSenderId: '936561383152',
    projectId: 'forbidden-area-app',
    storageBucket: 'forbidden-area-app.firebasestorage.app',
    iosBundleId: 'com.example.forbiddenAreaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBOC126zYedj8rXHbT-WdXs5NVcSucp2I',
    appId: '1:936561383152:web:0234d017023d880b61d435',
    messagingSenderId: '936561383152',
    projectId: 'forbidden-area-app',
    authDomain: 'forbidden-area-app.firebaseapp.com',
    storageBucket: 'forbidden-area-app.firebasestorage.app',
    measurementId: 'G-QEGRS77T9Q',
  );
}
